# 0ctf 2016 piapiapia
version: "2"

services:

  web:
    build: .
    image: ctftraining/0ctf_2016_unserialize
    environment:
      - FLAG=flag{e1a1237d-dc97-4c2f-841a-5b53deeecc90}
    restart: always
    ports:
      #- "127.0.0.1:8302:80"
      - "8302:80"
